# Generated by Django 4.0.3 on 2022-08-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('img', models.CharField(max_length=80)),
                ('review', models.TextField(default='default', max_length=256)),
                ('price', models.CharField(default='default', max_length=80)),
            ],
        ),
    ]
